[package]
name = "chdm"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["cargo", "derive"] }
ctrlc = "3.5.1"
cursive = "0.21.1"
greetd_ipc = { version = "0.10.3", features = ["tokio"] }
log = "0.4.29"
tokio = { version = "1.48.0", features = ["full"] }
